import React, { useMemo, useState } from "react";
import type { CanonicalCard } from "../../domain/card-catalog";
import { STARTER_DECK } from "../../domain/starter-deck";
import { EmeraldWorldSkin } from "../../components/EmeraldWorldSkin";
import { EmeraldWorldNav } from "../../components/EmeraldWorldNav";
import { EmeraldCardFrame } from "../../components/EmeraldCardFrame";
import { EmeraldBoosterPack } from "../../components/EmeraldBoosterPack";
import { applyBoosterOpening, applyStarterSet, collectionPercent, ownedCollection, playableCollection, type BoosterOpening, type BoosterOpenResponse } from "./model";

export interface CardVaultProps { cards: CanonicalCard[]; initialBalance: number; initialOwnedCardIds: string[]; priceCoins: number; initialStarterClaimed: boolean; }
export function CardVault({cards,initialBalance,initialOwnedCardIds,priceCoins,initialStarterClaimed}:CardVaultProps){
 const [tab,setTab]=useState<"collection"|"booster">("collection"),[balance,setBalance]=useState(initialBalance),[ownedIds,setOwnedIds]=useState(()=>new Set(initialOwnedCardIds)),[opening,setOpening]=useState<BoosterOpening|null>(null),[revealCount,setRevealCount]=useState(0),[openingBooster,setOpeningBooster]=useState(false),[boosterError,setBoosterError]=useState<string|null>(null),[starterClaimed,setStarterClaimed]=useState(initialStarterClaimed),[claimingStarter,setClaimingStarter]=useState(false),[starterError,setStarterError]=useState<string|null>(null);
 const collectibleCards=useMemo(()=>playableCollection(cards),[cards]),ownedCards=useMemo(()=>ownedCollection(cards,ownedIds),[cards,ownedIds]),percent=collectionPercent(ownedCards.length,collectibleCards.length),missingCoins=Math.max(0,priceCoins-balance);
 async function claimStarterSet(){if(claimingStarter||starterClaimed)return;setClaimingStarter(true);setStarterError(null);try{const response=await fetch("/api/starter-set/claim",{method:"POST"}),body=await response.json();if(!response.ok)throw new Error(body.error??"Das Starter Set konnte nicht gesichert werden.");setStarterClaimed(true);setOwnedIds(current=>applyStarterSet(current));}catch(error){setStarterError(error instanceof Error?error.message:"Das Starter Set konnte nicht gesichert werden.");}finally{setClaimingStarter(false)}}
 async function openBooster(){if(openingBooster||balance<priceCoins)return;setOpeningBooster(true);setBoosterError(null);try{const response=await fetch("/api/boosters/open",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({idempotencyKey:crypto.randomUUID()})}),body:BoosterOpenResponse=await response.json();if(!response.ok||!body.opening)throw new Error(body.error??"Der Booster konnte nicht geöffnet werden.");setOpening(body.opening);setRevealCount(0);setBalance(body.opening.balanceAfter);setOwnedIds(current=>applyBoosterOpening(current,body.opening!));}catch(error){setBoosterError(error instanceof Error?error.message:"Der Booster konnte nicht geöffnet werden.");}finally{setOpeningBooster(false)}}
 return <main className="bw-world score-shell min-h-dvh overflow-x-hidden text-foreground" data-design-pass="emerald-world-pass-03"><EmeraldWorldSkin/><div className="bw-page safe-page"><header className="bw-topbar"><a href="/" className="bw-brand">BIRDIEWORLD<small>THE NEST · FIRST EDITION</small></a><span className="bw-coin">● <strong>{balance}</strong> Coins</span></header><section className="bw-hero"><p className="bw-kicker">Collectibles from the Emerald World</p><h1 className="bw-title">The Nest</h1><p className="bw-copy">Familie, Rarität und Auswahl werden Teil derselben organischen Emerald-/Gold-Sprache wie die Golfwelt.</p></section><nav className="bw-segment mt-6"><button onClick={()=>setTab("collection")} aria-pressed={tab==="collection"}>Sammlung</button><button onClick={()=>setTab("booster")} aria-pressed={tab==="booster"}>Booster</button></nav>
 {tab==="collection"?<section className="mt-7"><div className="bw-panel mb-5 p-5 sm:p-7"><p className="bw-kicker">Dein Einstieg</p><h2 className="mt-2 text-2xl font-semibold">{STARTER_DECK.name}</h2><p className="mt-2 text-sm text-moss">1 Spieler · 4 Schläger · 3 Bälle · 17 einzigartige Aktionskarten.</p><button disabled={claimingStarter||starterClaimed} onClick={claimStarterSet} className="bw-gold-button mt-5">{starterClaimed?"Starter Set gesichert":claimingStarter?"Starter Set wird gesichert …":starterError?"Erneut versuchen":"Starter Set sichern"}</button>{starterError&&<p role="alert">{starterError}</p>}</div><div className="bw-panel p-5 sm:p-7"><div className="flex justify-between"><div><p className="bw-kicker">Sammlungsfortschritt</p><h2 className="mt-2 text-2xl font-semibold">{ownedCards.length} von {collectibleCards.length} Karten</h2></div><strong>{percent}%</strong></div><div className="bw-progress mt-4" role="progressbar" aria-valuenow={percent} aria-valuemin={0} aria-valuemax={100}><span style={{width:`${percent}%`}}/></div><div className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-3">{ownedCards.map(card=><EmeraldCardFrame key={card.id} card={card} interactive/>)}</div></div></section>:
 <section className="mt-7 grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><div className="bw-panel p-5 sm:p-7"><div className="bw-booster-stage"><EmeraldBoosterPack opening={openingBooster}/></div><p className="bw-kicker mt-7">Digitaler Booster</p><h2 className="mt-2 text-3xl font-semibold">1. Edition · 3 Karten</h2><p className="mt-3 text-sm text-moss">Neue Karten gehen in deine Sammlung. Doppelte Karten werden weiterhin serverseitig in Birdie Coins umgewandelt.</p><div className="mt-6 flex justify-between"><span>Launch-Beta-Preis</span><strong>{priceCoins} Coins</strong></div><button disabled={openingBooster||balance<priceCoins} onClick={openBooster} className="bw-emerald-button mt-5 w-full">{openingBooster?"Booster wird geöffnet …":"3er-Booster öffnen"}</button>{missingCoins>0&&<p className="mt-3 text-sm text-moss">Dir fehlen noch {missingCoins} Birdie Coins.</p>}{boosterError&&<p role="alert">{boosterError}</p>}</div><div className="bw-panel p-5 sm:p-7"><p className="bw-kicker">Booster Reveal</p><h2 className="mt-2 text-2xl font-semibold">Drei Artefakte aus deiner Welt.</h2>{!opening?<p className="mt-5 text-sm text-moss">Öffne einen Booster, um drei Karten aufzudecken.</p>:<><div className="mt-5 grid gap-4 sm:grid-cols-3">{opening.cards.map((entry,index)=>index<revealCount?<EmeraldCardFrame key={entry.slot} card={entry.card} outcome={entry.outcome==="new"?"new":"duplicate"}/>:<button key={entry.slot} disabled={index!==revealCount} onClick={()=>setRevealCount(index+1)} className="bw-reveal-slot disabled:opacity-50"><EmeraldBoosterPack/><span className="mt-3 block text-xs">{index===revealCount?`Karte ${index+1} aufdecken`:`Karte ${index+1} wartet`}</span></button>)}</div><button className="bw-gold-button mt-5" onClick={()=>setRevealCount(opening.cards.length)} disabled={revealCount===opening.cards.length}>Alle aufdecken</button></>}</div></section>}<EmeraldWorldNav active="cards"/></div></main>;
}
