import test from "node:test";
import assert from "node:assert/strict";
import {createOutreachPlane} from "../src/meta/outreach.mjs";

function harness({eligible=true,permission=true,providerResult={message_id:"mid.sent.1"}}={}){
 const rows=[]; let sends=0;
 const ledger={async appendIdempotent(r){const x=rows.find(v=>v.idempotencyKey===r.idempotencyKey);if(x)return x;rows.push({...r});return rows.at(-1)},async findByIdempotencyKey(k){return rows.find(v=>v.idempotencyKey===k)},async findByProviderMessageId(k){return rows.find(v=>v.providerMessageId===k)},async patch(id,p){const x=rows.find(v=>v.outreachEventId===id);Object.assign(x,p);return x}};
 const plane=createOutreachPlane({ledger,assetRegistry:{async get(id){return id==="ASSET-COIN-V1"?{state:"RELEASED",mimeType:"image/png",providerUrl:"https://approved.invalid/coin.png"}:null}},eligibilityReader:async()=>({state:eligible?"ELIGIBLE":"CLOSED"}),permissionReader:async()=>({instagram_manage_messages:permission}),providerSend:async(body)=>{sends++;assert.equal(body.message.attachment.type,"image");return providerResult},now:()=>Date.parse("2026-08-15T16:00:00Z")});
 return {plane,rows,get sends(){return sends}};
}

test("eligible registered image creates one intent, one receipt and replay sends nothing",async()=>{const h=harness();const input={recipientScopedId:"1789",instagramHandle:"@birdie.test",triggerEventId:"T1",assetReleaseId:"ASSET-COIN-V1"};const a=await h.plane.sendRegisteredImage(input);const b=await h.plane.sendRegisteredImage(input);assert.equal(a.event.sendStatus,"SENT");assert.equal(a.event.providerMessageId,"mid.sent.1");assert.equal(b.idempotent,true);assert.equal(h.sends,1);assert.equal(h.rows.length,1)});
test("closed conversation and missing permission fail before provider",async()=>{for(const opts of [{eligible:false},{permission:false}]){const h=harness(opts);await assert.rejects(()=>h.plane.sendRegisteredImage({recipientScopedId:"1789",instagramHandle:"birdie.test",assetReleaseId:"ASSET-COIN-V1"}));assert.equal(h.sends,0);assert.equal(h.rows.length,0)}});
test("unregistered asset is blocked",async()=>{const h=harness();await assert.rejects(()=>h.plane.sendRegisteredImage({recipientScopedId:"1789",instagramHandle:"birdie.test",assetReleaseId:"https://evil.invalid/x.png"}),/registered released/);assert.equal(h.sends,0)});
test("echo correlates once; unknown and conflicting echo quarantine",async()=>{const h=harness();const sent=await h.plane.sendRegisteredImage({recipientScopedId:"1789",instagramHandle:"birdie.test",assetReleaseId:"ASSET-COIN-V1"});const e=await h.plane.recordEcho({providerMessageId:sent.event.providerMessageId,echoMessageId:"echo.1",timestamp:"2026-08-15T16:01:00Z"});assert.equal(e.sendStatus,"ECHO_CONFIRMED");await h.plane.recordEcho({providerMessageId:"unknown.1",echoMessageId:"echo.x",timestamp:"2026-08-15T16:02:00Z"});await h.plane.recordEcho({providerMessageId:sent.event.providerMessageId,echoMessageId:"echo.2",timestamp:"2026-08-15T16:03:00Z"});assert.equal(h.rows.filter(r=>r.sendStatus==="ECHO_QUARANTINED").length,2)});
test("manual STICKER_SENT is idempotent and non-economic",async()=>{const h=harness();const a=await h.plane.stickerSent({instagramHandle:"@birdie.test",assetReleaseId:"ASSET-COIN-V1"});const b=await h.plane.stickerSent({instagramHandle:"birdie.test",assetReleaseId:"ASSET-COIN-V1"});assert.equal(a.event.sendStatus,"SENT_ATTESTED");assert.equal(b.idempotent,true);assert.equal(h.rows.length,1);assert.equal("birdieId" in a.event,false);assert.equal("points" in a.event,false)});
test("onboarding accepts quick reply and keyword but never writes Coin",()=>{const h=harness();for(const text of ["BIRDIE","CLAIM MY BIRDIE"]){const x=h.plane.onboardingIntent(text);assert.equal(x.claimType,"IDENTITY_WELCOME_CLAIM");assert.equal(x.coinWriteAllowed,false)}assert.equal(h.plane.onboardingIntent("LIKE"),null)});
test("tenfold replay creates zero extra sends or ledger rows",async()=>{const h=harness();const input={recipientScopedId:"1789",instagramHandle:"birdie.test",triggerEventId:"T1",assetReleaseId:"ASSET-COIN-V1"};for(let i=0;i<10;i++)await h.plane.sendRegisteredImage(input);assert.equal(h.sends,1);assert.equal(h.rows.length,1)});
