import React from "react";
export const EMERALD_MOTION_CSS = `
.bw-floating-hand{transition:opacity .28s ease,transform .36s ease}.bw-play-world[data-shot-phase=swing] .bw-floating-hand,.bw-play-world[data-shot-phase=flight] .bw-floating-hand{opacity:.24;transform:translateY(16px);pointer-events:none}.bw-play-world[data-shot-phase=settle] .bw-floating-hand{opacity:.6;transform:translateY(7px)}
.bw-shot-atmosphere{position:absolute;z-index:2;inset:0;overflow:hidden;border-radius:30px;pointer-events:none}.bw-shot-vein{position:absolute;height:1px;opacity:.12;background:linear-gradient(90deg,transparent,#e3bb5e 25%,#f5dc91 52%,transparent)}.vein-a{width:70%;left:-12%;bottom:25%;transform:rotate(-7deg)}.vein-b{width:58%;right:-14%;top:31%;transform:rotate(164deg)}.bw-shot-pulse{position:absolute;width:12px;height:12px;left:14%;bottom:26%;border:1px solid #f1d37c;border-radius:50%;opacity:0}.bw-shot-atmosphere[data-shot-phase=swing] .bw-shot-vein{animation:bw-vein-charge .24s ease-out both}.bw-shot-atmosphere[data-shot-phase=flight] .bw-shot-vein{animation:bw-vein-travel 1.2s ease-in-out infinite}.bw-shot-atmosphere[data-shot-phase=swing] .bw-shot-pulse{animation:bw-shot-pulse .24s ease-out both}.bw-result-rift{opacity:1;transform:none}.bw-play-world[data-shot-phase=result] .bw-result-rift{animation:bw-rift-arrive .36s ease-out both}.bw-play-world[data-motion-paused=true] *,.bw-play-world[data-motion-paused=true] *::before{animation-play-state:paused!important}
@keyframes bw-vein-charge{from{opacity:.1}to{opacity:.55}}@keyframes bw-vein-travel{0%,100%{opacity:.3}50%{opacity:.8}}@keyframes bw-shot-pulse{from{opacity:1;scale:1}to{opacity:0;scale:4}}@keyframes bw-rift-arrive{from{opacity:0;translate:12px 0}to{opacity:1;translate:0 0}}
.bw-play-world[data-reduced-motion=true] .bw-floating-hand{opacity:1!important;transform:none!important;transition:none!important;pointer-events:auto}.bw-play-world[data-reduced-motion=true] .bw-shot-atmosphere{display:none}.bw-play-world[data-reduced-motion=true] .bw-result-rift{animation:none;opacity:1;transform:none}
/* Pass 06: preserve readable cards and equipment on touch-sized viewports. */
.bw-course-stage{position:relative}.bw-floating-hand{position:relative;z-index:3;display:block;margin:12px 0 0}.bw-floating-hand-label{display:flex;align-items:baseline;gap:12px;color:var(--bw-gold);font-size:11px;letter-spacing:.12em}.bw-floating-hand-cards{display:flex;align-items:flex-start;justify-content:flex-start;gap:12px;max-width:100%;overflow-x:auto;padding:12px 4px 24px;scroll-snap-type:x proximity}.bw-floating-card,.bw-floating-card:first-child{flex:0 0 144px;width:144px;min-width:0;margin:0;transform:none;filter:none;scroll-snap-align:start}.bw-floating-card:hover{transform:none}.bw-hand-rules{padding:8px 3px;color:var(--bw-moss);font-size:12px;line-height:1.5}.bw-hand-rules summary{min-height:44px;display:flex;align-items:center;cursor:pointer}.bw-result-rift{position:absolute;z-index:4;right:18px;bottom:145px;width:min(320px,80%);padding:16px 22px;border-left:1px solid #e1ba60;border-radius:22px 22px 22px 6px;background:#03150ef2;box-shadow:0 12px 30px #0005;pointer-events:none}.bw-result-rift span{font-size:10px;letter-spacing:.16em;color:var(--bw-moss)}.bw-result-rift strong{display:block;margin:5px 0;font:400 24px/1.15 Georgia,serif;color:var(--bw-gold-soft)}.bw-result-rift small{font-size:12px;line-height:1.5}.bw-loadout-vein{display:block;margin-top:18px;padding-top:18px;border-top:1px solid var(--bw-line)}.bw-loadout-vein summary{min-height:48px;cursor:pointer}.bw-loadout-vein .bw-game-card-strip{grid-template-columns:repeat(auto-fit,minmax(125px,155px));margin:14px 0}.bw-play-options{display:flex;flex-wrap:wrap;gap:14px;align-items:center;justify-content:space-between}.bw-play-options label{display:flex;gap:9px;align-items:center;min-height:48px;font-size:13px}.bw-play-options input{accent-color:#d8b765}
@media(max-width:700px){.bw-floating-hand{margin:12px 0 0}.bw-floating-hand-label{display:flex}.bw-floating-card{width:144px}.bw-result-rift{right:12px;bottom:160px;padding:13px 17px}.bw-result-rift strong{font-size:20px}.bw-play-options{display:grid;grid-template-columns:1fr}}
@media(prefers-reduced-motion:reduce){.bw-floating-hand{opacity:1!important;transform:none!important;transition:none!important;pointer-events:auto!important}.bw-shot-atmosphere{display:none}.bw-result-rift{animation:none!important;opacity:1;transform:none}}
`;
export function EmeraldWorldPass05Skin() {
  return <style data-birdieworld-pass="emerald-world-pass-06-motion">{EMERALD_MOTION_CSS}</style>;
}
