import React, { useMemo, useState } from "react";
import type { CanonicalCard } from "../../domain/card-catalog";
import { CARD_BY_ID } from "../../domain/card-catalog";
import { EmeraldWorldSkin } from "../../components/EmeraldWorldSkin";
import { EmeraldWorldNav } from "../../components/EmeraldWorldNav";
import { EmeraldCardFrame } from "../../components/EmeraldCardFrame";
import { createInitialGameCardState, drawAtHoleStart, type GameCardState } from "./card-state";
import { CourseScene } from "./CourseScene"; import { COURSE_HOLES } from "./shot-engine"; import type { CourseShot } from "./course-flight";
export interface RecoveredGameLoadout {playerCardId:string;playerName:string;deckName:string;player:CanonicalCard;clubs:CanonicalCard[];balls:CanonicalCard[];actions:CanonicalCard[];}
function cardsFromIds(ids:readonly string[]):CanonicalCard[]{return ids.map(id=>CARD_BY_ID.get(id)).filter(Boolean) as CanonicalCard[]}
export function GameApp({loadout,courseShot}:{loadout:RecoveredGameLoadout;courseShot?:CourseShot}){const [cardState,setCardState]=useState<GameCardState>(()=>createInitialGameCardState(loadout)),[hole,setHole]=useState(1),[message,setMessage]=useState("Equipment liegt · 5er-Starthand bereit");const installedClubs=useMemo(()=>cardsFromIds(cardState.installedClubIds),[cardState]),installedBalls=useMemo(()=>cardsFromIds(cardState.installedBallIds),[cardState]),hand=useMemo(()=>cardsFromIds(cardState.handIds),[cardState]);
 function drawForNextHole(){if(hole>=6)return;setCardState(current=>{const next:GameCardState={drawPileIds:[...current.drawPileIds],handIds:[...current.handIds],installedClubIds:[...current.installedClubIds],installedBallIds:[...current.installedBallIds],discardIds:[...current.discardIds]};const resolution=drawAtHoleStart(next),drawnAction=resolution.actionIds[0]?CARD_BY_ID.get(resolution.actionIds[0]):null,installed=[...resolution.installedClubIds.map(id=>CARD_BY_ID.get(id)?.name),...resolution.installedBallIds.map(id=>CARD_BY_ID.get(id)?.name)].filter(Boolean);setMessage(drawnAction?`Loch ${hole+1} · ${drawnAction.name} gezogen`:installed.length?`Loch ${hole+1} · Equipment installiert: ${installed.join(", ")}`:`Loch ${hole+1} · kein weiterer Draw`);return next});setHole(value=>Math.min(6,value+1))}
 return <main className="bw-world min-h-screen" data-recovery-status="CARD_LAYER_RECOVERED" data-design-pass="emerald-world-pass-03"><EmeraldWorldSkin/><div className="bw-page"><header className="bw-topbar"><div className="bw-brand">BIRDIEWORLD<small>PLAY · EMERALD COURSE</small></div><div className="text-right"><strong>Loch {hole}/6</strong><p className="bw-note">{message}</p></div></header><section className="bw-hero"><p className="bw-kicker">Jeder Schlag zählt</p><h1 className="bw-title">{COURSE_HOLES[hole-1]?.name??"Emerald Course"}</h1><p className="bw-copy">Bahn und Karten sind jetzt Teile derselben Welt: organische Tiefe, dunkles Emerald und Gold nur an den entscheidenden Kanten.</p></section><CourseScene hole={COURSE_HOLES[hole-1]} shot={courseShot}/><section className="mt-5 grid gap-5 lg:grid-cols-[220px_1fr]"><aside className="bw-panel p-4"><p className="bw-kicker">Spieler</p><div className="mt-3"><EmeraldCardFrame card={loadout.player} compact/></div><h1 className="mt-3 font-serif text-xl">{loadout.playerName}</h1><p className="text-xs text-moss">{loadout.deckName}</p></aside><div className="grid gap-5"><section className="bw-panel p-4"><div className="flex justify-between"><div><p className="bw-kicker">Equipment</p><h2>Aktives Bag</h2></div><span className="text-xs text-moss">{installedClubs.length} Schläger · {installedBalls.length} Bälle</span></div><div className="bw-game-card-strip mt-4">{[...installedClubs,...installedBalls].map(card=><EmeraldCardFrame key={card.id} card={card} compact/>)}</div></section><section className="bw-panel p-4"><div className="flex justify-between"><div><p className="bw-kicker">Deine Optionen</p><h2>Aktionshand</h2></div><span className="text-xs text-moss">{hand.length} Karten</span></div><div className="bw-game-card-strip mt-4">{hand.map(card=><EmeraldCardFrame key={card.id} card={card} compact interactive/>)}</div></section><div className="flex justify-end"><button onClick={drawForNextHole} disabled={hole>=6} className="bw-gold-button">{hole>=6?"Loch 6 erreicht":"Nächstes Loch · Draw"}</button></div></div></section><EmeraldWorldNav active="play"/></div></main>}
